baseURL = "https://quickshell.outfoxxed.me"
languageCode = "en-us"
title = "Quickshell"
theme = "hextra"

[params.theme]
default = "dark"
displayToggle = true

[params.search]
enable = true
type = "flexsearch"
flexsearch.index = "content"

[params.navbar]
displayLogo = false

[params.page]
width = "wide"

[markup] # required by theme to render properly
goldmark.renderer.unsafe = true
highlight.noClasses = false

[[menu.sidebar]]
name = "QtQuick Type Reference ↗"
url = "https://doc.qt.io/qt-6/qtquick-qmlmodule.html"

[[menu.sidebar]]
name = "Quickshell Examples ↗"
url = "https://git.outfoxxed.me/outfoxxed/quickshell-examples"

[[menu.main]]
name = "Configuration"
pageRef = "/docs/configuration"
weight = 1

[[menu.main]]
name = "Types"
pageRef = "/docs/types"
weight = 2

[[menu.main]]
name = "Source ↗"
url = "https://git.outfoxxed.me/outfoxxed/quickshell"
weight = 3

[[menu.main]]
name = "Search"
weight = 4
params.type = "search"
